export const ADD_VIDEOGAMES = 'ADD_VIDEOGAMES';
export const ADD_GENRES = 'ADD_GENRES';
export const ADD_PLATFORMS = 'ADD_PLATFORMS';


export const DEL_FILTER = 'DEL_FILTER';
export const DEL_ALL_FILTERS = 'DEL_ALL_FILTERS';

export const LOADING = 'LOADING';

export const CLEAR_ALL = 'CLEAR_ALL';

export const ADD_VIDEOGAME = 'ADD_VIDEOGAME';
export const CLEAR_SELECTED_FILTERS = 'CLEAR_SELECTED_FILTERS';

export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS';
export const GET_SELECTED_FILTERS = 'GET_SELECTED_FILTERS';
export const SET_SELECTED_FILTERS = 'SET_SELECTED_FILTERS';
export const PUT_SELECTED_FILTERS = 'PUT_SELECTED_FILTERS';

export const SET_ALL_FILTERS = 'SET_ALL_FILTERS';

export const GET_VIDEOGAMES_FILTERED = 'GET_VIDEOGAMES_FILTERED';

