export const ADD_VIDEOGAMES = 'ADD_VIDEOGAMES';
export const ADD_GENRES = 'ADD_GENRES';
export const ADD_PLATFORMS = 'ADD_PLATFORMS';

export const GET_VIDEOGAMES_BY_NAME = 'GET_VIDEOGAMES_BY_NAME';

export const DEL_FILTER_NAME = 'DEL_FILTER_NAME';

export const REGENERATE_FILTERS = 'REGENERATE_FILTERS';

export const LOADING = 'LOADING';

export const CLEAR_ALL = 'CLEAR_ALL';

export const ADD_VIDEOGAME = 'ADD_VIDEOGAME';

export const GET_SELECTED_GENRES = 'GET_SELECTED_GENRES';
export const SET_SELECTED_GENRES = 'SET_SELECTED_GENRES';
export const PUT_SELECTED_GENRES = 'PUT_SELECTED_GENRES';

export const GET_SELECTED_PLATFORMS = 'GET_SELECTED_PLATFORMS';
export const SET_SELECTED_PLATFORMS = 'SET_SELECTED_PLATFORMS';
export const PUT_SELECTED_PLATFORMS = 'PUT_SELECTED_PLATFORMS';

export const GET_SELECTED_YEARS = 'GET_SELECTED_YEARS';
export const SET_SELECTED_YEARS = 'SET_SELECTED_YEARS';
export const PUT_SELECTED_YEARS = 'PUT_SELECTED_YEARS';

export const GET_SELECTED_SOURCES = 'GET_SELECTED_SOURCES';
export const SET_SELECTED_SOURCES = 'SET_SELECTED_SOURCES';
export const PUT_SELECTED_SOURCES = 'PUT_SELECTED_SOURCES';